# Generated by Django 5.0 on 2023-12-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myclass',
            name='speed',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
