# Generated by Django 5.0 on 2023-12-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_myclass_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclass',
            name='speed',
            field=models.CharField(blank=True, default=1, max_length=4, null=True),
        ),
    ]
