# Generated by Django 5.0 on 2023-12-14 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0004_myclass_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myclass',
            name='file',
        ),
    ]
