# Generated by Django 5.0 on 2023-12-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0005_remove_myclass_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclass',
            name='request',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
