# Generated by Django 5.0 on 2023-12-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0009_alter_myclass_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclass',
            name='request',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myclass',
            name='speed',
            field=models.CharField(default=1, max_length=4),
        ),
    ]
