# Generated by Django 5.0 on 2023-12-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0010_alter_myclass_request_alter_myclass_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclass',
            name='request',
            field=models.CharField(default='Empty', max_length=256),
        ),
        migrations.AlterField(
            model_name='myclass',
            name='speed',
            field=models.CharField(blank=True, default=1, max_length=4, null=True),
        ),
    ]
