# Generated by Django 5.0 on 2023-12-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0011_alter_myclass_request_alter_myclass_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclass',
            name='request',
            field=models.CharField(blank=True, default='Empty', max_length=256, null=True),
        ),
    ]
