# Generated by Django 5.0 on 2023-12-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0015_remove_myclass_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='myclass',
            name='speed',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
